// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPolizasVida.DataAccess;

#nullable disable

namespace RegistroPolizasVida.DataAccess.Migrations
{
    [DbContext(typeof(RegistroPolizasVidaDbContext))]
    partial class RegistroPolizasVidaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.ArchivoLote", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("CantidadPolizas")
                    .HasColumnType("int");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<Guid>("LoteCargaId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("NombreArchivo")
                    .IsRequired()
                    .HasMaxLength(260)
                    .HasColumnType("nvarchar(260)");

                b.Property<int>("PolizasActualizadas")
                    .HasColumnType("int");

                b.Property<int>("PolizasConError")
                    .HasColumnType("int");

                b.Property<int>("PolizasInsertadas")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("LoteCargaId");

                b.ToTable("ArchivosLote", (string)null);
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Asegurado", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Cedula")
                    .IsRequired()
                    .HasMaxLength(12)
                    .HasColumnType("nvarchar(12)");

                b.Property<string>("Correo")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<DateOnly>("FechaNacimiento")
                    .HasColumnType("date");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PolizaNumero")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("PrimerApellido")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("SegundoApellido")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Telefono")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("Id");

                b.HasIndex("Cedula");

                b.HasIndex("PolizaNumero");

                b.ToTable("Asegurados", (string)null);
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Beneficiario", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("AseguradoId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Cedula")
                    .HasMaxLength(12)
                    .HasColumnType("nvarchar(12)");

                b.Property<string>("CedulaJuridica")
                    .HasMaxLength(12)
                    .HasColumnType("nvarchar(12)");

                b.Property<string>("Correo")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<decimal>("PorcentajeBeneficio")
                    .HasColumnType("decimal(5,2)");

                b.Property<string>("PrimerApellido")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("RazonSocial")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("SegundoApellido")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Telefono")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("TipoPersona")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id");

                b.HasIndex("AseguradoId");

                b.ToTable("Beneficiarios", (string)null);
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.ErrorProcesamiento", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ArchivoLoteId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("FechaError")
                    .HasColumnType("datetime2");

                b.Property<int?>("Linea")
                    .HasColumnType("int");

                b.Property<string>("Mensaje")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("NumeroPoliza")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("Id");

                b.HasIndex("ArchivoLoteId");

                b.ToTable("ErroresProcesamiento", (string)null);
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.LoteCarga", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("ArchivosProcesados")
                    .HasColumnType("int");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime>("FechaCarga")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("FechaFinProcesamiento")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("FechaInicioProcesamiento")
                    .HasColumnType("datetime2");

                b.Property<string>("NombreArchivoZip")
                    .IsRequired()
                    .HasMaxLength(260)
                    .HasColumnType("nvarchar(260)");

                b.Property<int>("PolizasActualizadas")
                    .HasColumnType("int");

                b.Property<int>("PolizasConError")
                    .HasColumnType("int");

                b.Property<int>("PolizasInsertadas")
                    .HasColumnType("int");

                b.Property<int>("TotalArchivos")
                    .HasColumnType("int");

                b.Property<int>("TotalPolizas")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("FechaCarga");

                b.ToTable("LotesCarga", (string)null);
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Poliza", b =>
            {
                b.Property<string>("NumeroPoliza")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTime>("FechaActualizacion")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime2");

                b.Property<DateOnly>("FechaEmision")
                    .HasColumnType("date");

                b.Property<DateOnly>("FechaVencimiento")
                    .HasColumnType("date");

                b.Property<Guid>("LoteCargaOrigenId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("LoteCargaUltimaActualizacionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Moneda")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)");

                b.Property<decimal>("MontoCobertura")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("VersionActualizacion")
                    .HasColumnType("int");

                b.HasKey("NumeroPoliza");

                b.HasIndex("LoteCargaOrigenId");

                b.HasIndex("LoteCargaUltimaActualizacionId");

                b.ToTable("Polizas", (string)null);
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.ArchivoLote", b =>
            {
                b.HasOne("RegistroPolizasVida.Domain.Entities.LoteCarga", "LoteCarga")
                    .WithMany("Archivos")
                    .HasForeignKey("LoteCargaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LoteCarga");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Asegurado", b =>
            {
                b.HasOne("RegistroPolizasVida.Domain.Entities.Poliza", "Poliza")
                    .WithMany("Asegurados")
                    .HasForeignKey("PolizaNumero")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Poliza");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Beneficiario", b =>
            {
                b.HasOne("RegistroPolizasVida.Domain.Entities.Asegurado", "Asegurado")
                    .WithMany("Beneficiarios")
                    .HasForeignKey("AseguradoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Asegurado");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.ErrorProcesamiento", b =>
            {
                b.HasOne("RegistroPolizasVida.Domain.Entities.ArchivoLote", "ArchivoLote")
                    .WithMany("Errores")
                    .HasForeignKey("ArchivoLoteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ArchivoLote");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Poliza", b =>
            {
                b.OwnsOne("RegistroPolizasVida.Domain.Entities.Tomador", "Tomador", b1 =>
                {
                    b1.Property<string>("PolizaNumeroPoliza")
                        .HasColumnType("nvarchar(20)");

                    b1.Property<string>("Cedula")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Tomador_Cedula");

                    b1.Property<string>("CedulaJuridica")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Tomador_CedulaJuridica");

                    b1.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Tomador_Correo");

                    b1.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Tomador_Direccion");

                    b1.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Tomador_Nombre");

                    b1.Property<string>("PrimerApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tomador_PrimerApellido");

                    b1.Property<string>("RazonSocial")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Tomador_RazonSocial");

                    b1.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tomador_SegundoApellido");

                    b1.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Tomador_Telefono");

                    b1.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tomador_TipoPersona");

                    b1.HasKey("PolizaNumeroPoliza");

                    b1.ToTable("Polizas");

                    b1.WithOwner()
                        .HasForeignKey("PolizaNumeroPoliza");
                });

                b.Navigation("Tomador")
                    .IsRequired();
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.ArchivoLote", b =>
            {
                b.Navigation("Errores");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Asegurado", b =>
            {
                b.Navigation("Beneficiarios");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.LoteCarga", b =>
            {
                b.Navigation("Archivos");
            });

            modelBuilder.Entity("RegistroPolizasVida.Domain.Entities.Poliza", b =>
            {
                b.Navigation("Asegurados");
            });
#pragma warning restore 612, 618
        }
    }
}
